apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: my-application-2
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: nodejs-urgent-care1
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: nodejs-urgent-care1
  namespace: eyuen
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: nodejs-urgent-care1
status:
  configuration:
    generatedName: ""
