apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: nodejs-urgent-care1
  namespace: eyuen
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: my-application-2
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: nodejs-urgent-care1
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: nodejs-urgent-care1-
      labels:
        build.appstudio.openshift.io/application: my-application-2
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: nodejs-urgent-care1
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: eyuen
    spec:
      params:
      - name: git-url
        value: https://github.com/samburrai/urgent-care-finder-v2
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:eyuen-nodejs-urgent-care1-$(tt.params.git-revision)
      - name: dockerfile
        value: https://raw.githubusercontent.com/nodeshift-starters/devfile-sample/main/Dockerfile
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: nodejs-urgent-care1/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
