apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-urgent-care1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-urgent-care1
    app.kubernetes.io/part-of: my-application-2
  name: nodejs-urgent-care1
  namespace: eyuen
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nodejs-urgent-care1
    weight: 100
status: {}
